### ISSUE TITLE
bifurcate doesn't expand environment variables before executing

### ISSUE THREAD

**Issue by mterron** [novilabs/bifurcate#3]
If you put something like this in the config file, app is executed with ARG=$ENV instead of ARG=value.
Let's say there is an environment variable ENV=value

``` json
{
    "programs": {
        "app": {
            "args": ["app","ARG=$ENV"]
        }
    }
}
```

**Comment by camerondavison** [comment]
Yes. That is expected since everything is being bash escaped before running it. You can use {{env "ARG"}} since it runs it through a go template. Does that help you?

**Comment by mterron** [comment]
It does @a86c6f7964 , but it is a little unexpected. Any reason why you don't expand environment variables by default? It is the least surprising behaviour for an application launcher.
From your comment I take that my config should look like:

``` json
{
    "programs": {
        "app": {
            "args": ["app","ARG={{ env ENV }}"]
        }
    }
}
```

**Comment by camerondavison** [comment]
I could agree. The reason is that go is actually executing the command. Not
bash. If I wanted to interpolate the environment variables I would have to
run the command as an eval in the shell rather than straight through go. (I
believe)

**Comment by camerondavison** [comment]
Okay if I close this as won't fix?

**Comment by mterron** [comment]
Sure
Thanks

**Comment by mterron** [comment]
Is it possible to use a template in the required file? Something like:
```
{ 
"programs": {
  "app": {
        "requires": [
          {
            "file": "/{{ env DATA_DIR }}/file"
          }
        ],
        "args": ["/usr/local/bin/start_app.sh"]
      }
}
```

When I try to do this I get:
`Error reading template /etc/bifurcate/bifurcate.json template: config:21: function "DATA_DIR" not defined`
